-- comando para atualizar uma lista de produtos a partir de um pedaço da descrição
USE [HRM1]
GO

SELECT [CODIGO]
      ,[DESCRICAO]
  FROM [dbo].[MARCA_PRODUTO]
  ORDER BY DESCRICAO
GO

SELECT A.CODIGO, A.DESCRICAO, A.CODIGO_MARCA
FROM PRODUTO A WHERE A.DESCRICAO LIKE '%BRENTA%'

UPDATE PRODUTO
SET CODIGO_MARCA = 33
WHERE DESCRICAO LIKE '%BRENTA%';